dist: trusty
sudo: required
language:
  - cpp
compiler:
  - gcc
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-7
      - g++-7
      - libopenal-dev
      - libjpeg-dev
      - libudev-dev
      - libxrandr-dev
      - libfreetype6-dev
      - libvorbis-dev
      - libflac-dev
script:
  - echo "Installing SFML..."
  - pwd
  - ls
  - wget https://www.sfml-dev.org/files/SFML-2.5.1-sources.zip
  - unzip SFML-2.5.1-sources.zip > sfml-downloadlog
  - pwd
  - ls
  - cd SFML-2.5.1
  - mkdir build/
  - cd build
  - cmake -G"Unix Makefiles" -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=TRUE .. > install.log
  - make >> install.log
  - sudo make install >> install.log
  - sudo ldconfig
  - cd /home/travis/build/NikiGamePlay/niki-multigame
  - export CC=/usr/bin/gcc-7
  - export CXX=/usr/bin/g++-7
  - gcc -v && g++ -v && cmake --version
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_CXX_FLAGS="-std=c++17"
  - make
