dist: trusty
sudo: required
language:
  - cpp
compiler:
  - gcc
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-7
      - g++-7
      - libopenal-dev
      - libjpeg-dev
      - libudev-dev
      - libxrandr-dev
      - libfreetype6-dev
      - libvorbis-dev
      - libflac-dev
      - libsfml-dev
install:
  - git clone https://github.com/SFML/SFML.git
  - cd SFML
  - git checkout tags/2.5.1
  - mkdir install
  - mkdir build
  - cd build
  - cmake -DCMAKE_INSTALL_PREFIX=../install -DCMAKE_INSTALL_FRAMEWORK_PREFIX=../install -DSFML_BUILD_FRAMEWORKS=FALSE -DBUILD_SHARED_LIBS=TRUE ..
  - make
  - make install
  - cd ../../

script:
  - mkdir install
  - mkdir install/nikimultigame
  - cmake -DCMAKE_INSTALL_PREFIX=./install/nikimultigame -DSFML_DIR=./SFML/install -DCMAKE_MODULE_PATH=./SFML/cmake/Modules .
  - make
  - make install
